name: Build

env:
  include_paths: |
    docs/
    share/
    images/
    enigma_v5/
    tools/
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - 'enigma_v5/**.h'
      - 'enigma_v5/**.m'
      - '**/Makefile'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'enigma_v5/**.h'
      - 'enigma_v5/**.m'
      - '**/Makefile'
      - '.github/workflows/build.yml'

jobs:
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        shared: [0, 1]
    name: Build macOS (${{ matrix.shared == 0 && 'Static' || 'Shared' }})
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
          SHARED: ${{ matrix.shared }}
        run: make
      - name: Generate artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hashcat-macos-${{ matrix.shared == 0 && 'static' || 'shared' }}
          path: ${{ env.include_paths }}
