name: Build

env:
  include_paths: |
    enigma_v4
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - 'enigma_v4'
      - 'enigma_v4/**.h'
      - 'enigma_v4/**.c'
      - 'enigma_v4/Makefile'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - master
    paths:

      - 'enigma_v4'
      - 'enigma_v4/**.h'
      - 'enigma_v4/**.c'
      - 'enigma_v4/Makefile'
      - '.github/workflows/build.yml'

jobs:
  build-macos:
    strategy:
      fail-fast: false
      Kortin-Enigma:
        shared: [0, 1]
    name: Build macOS (${{ Kortin-Enigma.shared == 0 && 'Static' || 'Shared' }})
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          SHARED: ${{ Kortin-Enigma.shared }}
        run: make
      - name: Generate artifacts
        uses: actions/upload-artifact@v4
        with:
          name: enigma-macos-${{ Kortin-Enigma.shared == 0 && 'static' || 'shared' }}
          path: ${{ env.include_paths }}
